export default {
	primary: '#000',
	primaryBackground: '#edf5ff',
	accent: '#feca57',
	secondary: '#ffffff',
	secondaryText: '#c0c4cc',
	tertiary: '#e0e2e9',
	text: '#fff',
	window: '#f5f5f5',
	highlight: '#a4ccff',
	highlightBackground: '#f6faff',
	success: '#4caf50',
	successBackground: '#edf7ed',
	successLight: '#a0d4a7',
	danger: '#ef5350',
	dangerBackground: '#feeded',
	dangerLight: '#f7a3a2',
	star: '#fecb57',
}
